disabled_rules: # rule identifiers turned on by default to exclude from running
  - force_cast
  - force_try
  - line_length
  - class_delegate_protocol
  - todo
  - identifier_name
  - function_parameter_count
  - function_body_length
  - large_tuple
  - void_return
  - orphaned_doc_comment
  - unused_closure_parameter
  - unused_optional_binding
  - opening_brace
  - cyclomatic_complexity
  - colon
  - comment_spacing
  - comma
  - control_statement
  - multiple_closures_with_trailing_closure
  - implicit_getter
  - nesting
  - legacy_constructor
  - redundant_optional_initialization
  - trailing_newline
  - file_length
  - syntactic_sugar
  - for_where
  - trailing_semicolon
  - weak_delegate
