disabled_rules: # rule identifiers turned on by default to exclude from running
  - force_cast
  - force_try
  - line_length
  - class_delegate_protocol
  - todo
  - identifier_name
  - function_parameter_count
  - function_body_length
  - large_tuple
  - unused_closure_parameter
  - unused_optional_binding
  - opening_brace
  - cyclomatic_complexity
  - comment_spacing
  - control_statement
  - multiple_closures_with_trailing_closure
  - implicit_getter
  - nesting
  - legacy_constructor
  - redundant_optional_initialization
  - file_length
  - trailing_semicolon
  - weak_delegate
